omanges/turfpy

dev_requirements.txt, setup.cfg, tests/test_measurement.py, tox.ini, turfpy/helper.py, turfpy/measurement.py, turfpy/meta.py
I have made small changes in code related to type hints and as per python style and minor changes in CICD
=> refactored code

.travis.yml
=> Added python 3.9 build in travis-CI

tests/test_measurement.py, turfpy/dev_lib/spline.py, turfpy/measurement.py
=> Fixed LGTM issue

environment.yml, examples/measurements.ipynb, examples/transformations.ipynb
Added example notebooks, for now, will raise separate PR for the binder later.
=> Added example notebooks

tests/test_transformation.py, turfpy/transformation.py
=> updated union function

.isort.cfg, Makefile, docs/Makefile, docs/conf.py, docs/make.bat, tests/test_measurement.py, tests/test_transformation.py, turfpy/measurement.py, turfpy/transformation.py
=> Added docs changes

examples/measurements.ipynb, examples/requirements_examples.txt, measurements.md
=> :pencil: Added example notebook and docs for function points_within_polygon

setup.py, tests/test_transformation.py, transformation.md, turfpy/measurement.py, turfpy/transformation.py
Added changes for transform_rotate, transform_translate, transform_scale functionality
Related issue:- https://github.com/omanges/turfpy/issues/42
=> Added changes for transform_rotate, transform_translate, transform_scale functionality

docs/index.rst, docs/turfpy.dev_lib.earcut.rst, docs/turfpy.dev_lib.rst, examples/transformations.ipynb
=> 📝 Added example for tesselate in notebook

examples/transformations.ipynb, tests/test_transformation.py, transformation.md, turfpy/helper.py, turfpy/transformation.py
Added line_offset feature  for https://github.com/omanges/turfpy/issues/41
=> Added line_offset feature 

MANIFEST.in
It would be helpful to include the license file in the source distribution
=> Add license file to MANIFEST.in

README.md, setup.py, turfpy/__init__.py
=> Updated the title statement.

README.md, postBuild
=> Added badges

setup.py, tests/test_measurement.py, turfpy/__init__.py, turfpy/__version__.py, turfpy/measurement.py, turfpy/meta.py, turfpy/transformation.py
=> made version accessible at runtime

.readthedocs.yml
=> fixed docs build

turfpy/__version__.py
=> Bumped version to v0.0.5

.github/workflows/main.yml, .travis.yml, ci/env/environment.yml
for now, this will run all tests on windows, Mac, and Linux on Github actions and deploy on Travis. later we will move the deploy on Github actions as well.
=> Github actions for CI

.github/workflows/main.yml
=> Removed py36 from CI due to rounding issues in windows

tests/test_transformation.py, turfpy/helper.py
fix(line_offset): fix problem with negative distances
test(line_offset): add test to line_offset with linestring
The main problem was the module operation. this operation behaves differently on javascript and python. This fix generates the correct result.
=> Fix problem with negative distances on line_offset

tests/test_transformation.py, turfpy/transformation.py
When intersection has type=GeometryCollection, coordinates is undefined.
=> Bugfix: intersection may be GeometryCollection

tests/test_misc.py, turfpy/misc.py
Finally I implemented lineSlice() functionality and nearestPointOnLine() (as a dependency) based on turfjs idea to fulfill requirements in my project (#82). 
What is missing:
1. Examples - I'm not familiar with documentation platform (sphinx, jupyter, ...), so if you like, add example(s)
1. I'm quite new in turf* and geojson world, so if you see possible optimizations in my code, please modify it so I can learn something new
1. Tests - same as above - never done any pytest but I'll be glad to see how it should be done
=> Added Line Slice and Nearest Point on Line functionalities

turfpy/misc.py
This will fix the issue :- https://github.com/omanges/turfpy/issues/86
=> Added bug fix for line segment for multilinestring

tests/test_helper.py, tests/test_transformation.py, turfpy/helper.py, turfpy/transformation.py
=> fixed type checking in helper functions
